### ISSUE TITLE
Hipparcos Functions

### ISSUE THREAD

**Issue by digitalvapor** [brandon-rhodes/python-skyfield#35]
Hi, what is the usage of the [hipparcos.py](https://github.com/brandon-rhodes/python-skyfield/blob/master/skyfield/data/hipparcos.py) functions?

I see from the tests that I can do parsing of hipparcos lines.

```
line = 'H|       11767| |02 31 47.08|+89 15 50.9| 1.97|1|H|037.94614689|+89.26413805| |   7.56|   44.22|  -11.74|  0.39|  0.45|  0.48|  0.47|  0.55|-0.16| 0.05| 0.27|-0.01| 0.08| 0.05| 0.04|-0.12|-0.09|-0.36|  1| 1.22| 11767| 2.756|0.003| 2.067|0.003| | 0.636|0.003|T|0.70|0.00|L| | 2.1077|0.0021|0.014|102| | 2.09| 2.13|   3.97|P|1|A|02319+8915|I| 1| 1| | | |  |   |       |     |     |    |S| |P|  8890|B+88    8 |          |          |0.68|F7:Ib-IIv SB|G\n'
star = hipparcos.parse(line)
print(star.ra.hours, star.dec.degrees)
```

When I use `get`, I can download the hipparcos file. I think there needs to be another check for whether the file was downloaded. By default, when I use `load`, I get an error with `TypeError: coercing to Unicode: need string or buffer, file found`. If I instead use the following for the already downloaded file, I can open it without error.

```
gzip_file_handle = gzip.open('hip_main.dat.gz')
data = gzip_file_handle.readlines()
```

The above uses the shorthand of `gzip.open(f)`. If I substitute `gzip.GzipFile(fileobj=f)`, then I am able to read the lines of the file.

**Comment by brandon-rhodes** [comment]
Oh. Now that I have the chance to look at it, this is not a Unicode error at all. This is just my code completely failing to call the `gzip` library in the manner to which it is accustomed. I wonder if I ever finished this code and tried it out? It is not mentioned in the documentation yet, so I think it is still unfinished. The `parse()` routine had to work, so that I could test Skyfield against the USNO’s NOVAS library, but the rest had not come together yet.

But you are right: supplying the file as the `fileobj=` argument instead of as the default `filename=` argument fixes things right up. I will make the change right now.

I wonder whether `load()` should really pay attention only to the ID? Looking at this after a few weeks away, it looks more useful for `load()` to allow the `is_match()` function to see the whole line — what, after all, if the caller wants all stars of a given magnitude, or a given color or something, or above a given declination? I think I will make that change too!

**Comment by digitalvapor** [comment]
Super, I'm closing https://github.com/brandon-rhodes/python-skyfield/pull/36 then. :) Thanks for fixing, I was heavily using this function :+1:
