### ISSUE TITLE
ICRS.ecliptic_latlon returns weird results 

### ISSUE THREAD

**Issue by oefe** [brandon-rhodes/python-skyfield#41]
The `ICRS` class contains an undocumented function `ecliptic_latlon` which is supposed to return ecliptic latitude, longitude, and distance.

However, the results of this function don't appear plausible to me.

Here is an example, plotting the 1900-2049 orbit of Pluto projected in a plane perpendicular to the ecliptic:

```python
import numpy as np
import matplotlib.pyplot as plt

from skyfield.api import pluto, JulianDate
from skyfield.functions import from_polar

jd = JulianDate(utc=(range(1900,2050),))
pluto_orbit = pluto(jd)

# top: using ecliptic_latlon - wrong?
plt.subplot(211)
lat, lon, r = pluto_orbit.ecliptic_latlon()
pos = from_polar(r.AU, lat.radians, lon.radians)
plt.scatter(pos[0], pos[1], linewidths=(0,), marker='.')

# bottom: rotating it myself - right?
plt.subplot(212)
from skyfield.constants import ASEC2RAD, T0
from skyfield.functions import rot_x
from skyfield.nutationlib import mean_obliquity

epsilon = mean_obliquity(T0) * ASEC2RAD
rot_to_ecliptic = rot_x(epsilon)

pos = rot_to_ecliptic.dot(pluto_orbit.position.AU)
plt.scatter(pos[1], pos[2], linewidths=(0,), marker='.')

plt.show()
```

Here is the output:
![image](https://cloud.githubusercontent.com/assets/2773028/5748379/bd6a0d2c-9c3f-11e4-8655-214eb114bc46.jpg)

In the top plot (created using `ecliptic_latlon`) Pluto's orbit "bounces" on the ecliptic in a strange way.

In the bottm plot, (rotating the coordinates using code "stolen" from  `ecliptic_latlon`), the orbit looks like an ellipse, as I would expect it to be.

Disclaimer: I have zero experience in astronomy, and these are my first attempts with Skyfield,  so I it's very likely that i did something wrong. Maybe I messed up the polar to cartesian transformation?

Or maybe  `ecliptic_latlon` is undocumented on purpose?

**Comment by brandon-rhodes** [comment]
You have indeed found a bug!

But, it turns out, not in the undocumented `ecliptic_latlon()` method, which is working fine. It is in the undocumented, and apparently entirely unused and untested, `from_polar()` helper function, which — to its great embarrassment — has its θ and φ swapped.

I will go fix them.

**Comment by brandon-rhodes** [comment]
Not only should `from_polar()` not be working, but — because it seems ponderous that you are forced to ask for the ecliptic position in polar coordinates only to have to switch them back to x,y,z again — I have added an `ecliptic_position()` method next to `ecliptic_latlon()` that returns a vector instead:
```
x, y, z = pluto_orbit.ecliptic_position().AU
```
You can try out the development version of Skyfield with:
```
pip install https://github.com/brandon-rhodes/python-skyfield/archive/master.zip
```
Let me know whether things start working for you now — thanks for your patience in writing up this bug report so we could get this fixed!

**Comment by oefe** [comment]
Yeah, I wondered about this extra conversion as well.

Works like a charm! Thanks for the quick response.

**Comment by brandon-rhodes** [comment]
Great! I am going to go ahead and close this issue, and I hope to get a new Skyfield version out in the next week or two that makes this fix available to everyone. In the meantime you can install from the above link or just cut-and-paste the corrected `from_polar()` into your own code. Enjoy!
